neetcode = [
    "Two Sum",
    "Add Two Numbers",
    "Longest Substring Without Repeating Characters",
    "Median of Two Sorted Arrays",
    "Longest Palindromic Substring",
    "Coin Change II",
    "Reverse Integer",
    "Count Good Nodes in Binary Tree",
    "Regular Expression Matching",
    "Container With Most Water",
    "Rotting Oranges",
    "3Sum",
    "Letter Combinations of a Phone Number",
    "Remove Nth Node From End of List",
    "Valid Parentheses",
    "Merge Two Sorted Lists",
    "Generate Parentheses",
    "Merge k Sorted Lists",
    "Reverse Nodes in k-Group",
    "Diameter of Binary Tree",
    "Search in Rotated Sorted Array",
    "Valid Sudoku",
    "Combination Sum",
    "Combination Sum II",
    "Trapping Rain Water",
    "Multiply Strings",
    "Jump Game II",
    "Permutations",
    "Rotate Image",
    "Group Anagrams",
    "Pow(x, n)",
    "N-Queens",
    "Maximum Subarray",
    "Spiral Matrix",
    "Jump Game",
    "Merge Intervals",
    "Insert Interval",
    "Permutation in String",
    "Subtree of Another Tree",
    "Unique Paths",
    "Plus One",
    "Climbing Stairs",
    "Edit Distance",
    "Set Matrix Zeroes",
    "Search a 2D Matrix",
    "Minimum Window Substring",
    "Subsets",
    "Word Search",
    "Largest Rectangle in Histogram",
    "Subsets II",
    "Decode Ways",
    "Detect Squares",
    "Interleaving String",
    "Validate Binary Search Tree",
    "Same Tree",
    "Binary Tree Level Order Traversal",
    "Last Stone Weight",
    "Maximum Depth of Binary Tree",
    "Construct Binary Tree from Preorder and Inorder Traversal",
    "Task Scheduler",
    "Balanced Binary Tree",
    "Distinct Subsequences",
    "Best Time to Buy and Sell Stock",
    "Binary Tree Maximum Path Sum",
    "Valid Palindrome",
    "Word Ladder",
    "Longest Consecutive Sequence",
    "Surrounded Regions",
    "Palindrome Partitioning",
    "Clone Graph",
    "Gas Station",
    "Palindromic Substrings",
    "Single Number",
    "Copy List with Random Pointer",
    "Word Break",
    "Linked List Cycle",
    "Reorder List",
    "LRU Cache",
    "Evaluate Reverse Polish Notation",
    "Maximum Product Subarray",
    "Find Minimum in Rotated Sorted Array",
    "Min Stack",
    "Valid Parenthesis String",
    "Two Sum II - Input Array Is Sorted",
    "Min Cost to Connect All Points",
    "Redundant Connection",
    "Max Area of Island",
    "Reverse Bits",
    "Number of 1 Bits",
    "House Robber",
    "Binary Tree Right Side View",
    "Number of Islands",
    "Happy Number",
    "Reverse Linked List",
    "Course Schedule",
    "Implement Trie (Prefix Tree)",
    "Course Schedule II",
    "Design Add and Search Words Data Structure",
    "Word Search II",
    "House Robber II",
    "Kth Largest Element in an Array",
    "Contains Duplicate",
    "Invert Binary Tree",
    "Daily Temperatures",
    "Longest Common Subsequence",
    "Kth Smallest Element in a BST",
    "Network Delay Time",
    "Lowest Common Ancestor of a Binary Search Tree",
    "Min Cost Climbing Stairs",
    "Product of Array Except Self",
    "Sliding Window Maximum",
    "Valid Anagram",
    "Meeting Rooms",
    "Meeting Rooms II",
    "Partition Labels",
    "Graph Valid Tree",
    "Missing Number",
    "Alien Dictionary",
    "Encode and Decode Strings",
    "Kth Largest Element in a Stream",
    "Binary Search",
    "Swim in Rising Water",
    "Walls and Gates",
    "Find the Duplicate Number",
    "Cheapest Flights Within K Stops",
    "Find Median from Data Stream",
    "Serialize and Deserialize Binary Tree",
    "Longest Increasing Subsequence",
    "Best Time to Buy and Sell Stock with Cooldown",
    "Burst Balloons",
    "Coin Change",
    "Number of Connected Components in an Undirected Graph",
    "Longest Increasing Path in a Matrix",
    "Reconstruct Itinerary",
    "Counting Bits",
    "Top K Frequent Elements",
    "Design Twitter",
    "Hand of Straights",
    "Sum of Two Integers",
    "Car Fleet",
    "Koko Eating Bananas",
    "Partition Equal Subset Sum",
    "Pacific Atlantic Water Flow",
    "Longest Repeating Character Replacement",
    "Non-overlapping Intervals",
    "Minimum Interval to Include Each Query",
    "Merge Triplets to Form Target Triplet",
    "Target Sum",
    "K Closest Points to Origin",
    "Time Based Key-Value Store",
]


paypal = [
    "Zigzag Conversion",
    "LRU Cache",
    "Minimum Replacements to Sort the Array",
    "Count Vowel Strings in Ranges",
    "Count the Number of Vowel Strings in Range",
    "Meeting Scheduler",
    "Maximum Number of Integers to Choose From a Range I",
    "Number of Valid Move Combinations On Chessboard",
    "Word Search",
    "Time Needed to Rearrange a Binary String",
    "Number of Islands",
    "Maximum Frequency Score of a Subarray",
    "Minimum Non-Zero Product of the Array Elements",
    "Maximum Number of Integers to Choose From a Range II",
    "Paint House III",
    "Maximum Sum Obtained of Any Permutation",
    "Count Array Pairs Divisible by K",
    "Smallest Greater Multiple Made of Two Digits",
    "Best Time to Buy and Sell Stock",
    "Group Anagrams",
    "Longest Increasing Subsequence",
    "Maximal Square",
    "Two Sum",
    "Product of Array Except Self",
    "Coin Change",
    "Pairs of Songs With Total Durations Divisible by 60",
    "Longest Substring Without Repeating Characters",
    "Minimum Absolute Difference",
    "Merge Intervals",
    "Merge Sorted Array",
    "Subarray Sum Equals K",
    "Find the Smallest Divisor Given a Threshold",
    "Maximum Number of Events That Can Be Attended",
    "Loud and Rich",
    "Reorganize String",
    "Valid Anagram",
    "Count Vowel Substrings of a String",
    "Valid Parentheses",
    "Trapping Rain Water",
    "House Robber",
    "Meeting Rooms III",
    "Random Pick with Weight",
    "Sort Colors",
    "Last Stone Weight",
    "Top K Frequent Elements",
    "Minimum Increment to Make Array Unique",
    "Maximum Subarray",
    "Median of Two Sorted Arrays",
    "Kth Largest Element in an Array",
    "Rotate Image",
    "Koko Eating Bananas",
    "Palindromic Substrings",
    "Jump Game",
    "Text Justification",
    "Minimum Number of Swaps to Make the String Balanced",
    "3Sum Smaller",
    "Count and Say",
    "Subarray Product Less Than K",
    "Reverse Linked List",
    "Happy Number",
    "Find First and Last Position of Element in Sorted Array",
    "Search in Rotated Sorted Array",
    "Degree of an Array",
    "Valid Sudoku",
    "Flatten Deeply Nested Array",
    "LFU Cache",
    "3Sum",
    "Longest Consecutive Sequence",
    "Meeting Rooms II",
    "Squares of a Sorted Array",
    "Course Schedule",
    "Search a 2D Matrix II",
    "Maximum Profit in Job Scheduling",
    "Spiral Matrix",
    "Flatten Binary Tree to Linked List",
    "Find Median from Data Stream",
    "Find Pivot Index",
    "Path Sum",
    "Maximum Product Subarray",
    "Lexicographically Smallest Palindrome",
    "Maximum Population Year",
    "Min Stack",
    "Word Search II",
    "Delete Node in a Linked List",
    "Minimum Window Substring",
    "First Unique Character in a String",
    "Maximum Frequency Stack",
    "Invalid Transactions",
    "Container With Most Water",
    "Process Tasks Using Servers",
    "Find Peak Element",
    "Intersection of Two Arrays",
    "Find Minimum in Rotated Sorted Array",
    "Minimum Number of Removals to Make Mountain Array",
    "Divide Players Into Teams of Equal Skill",
    "Jump Game II",
    "Number of Substrings Containing All Three Characters",
    "First Missing Positive",
    "Merge In Between Linked Lists",
    "Design Twitter",
]
i = 0
for val in paypal:
    if val in neetcode:
        print(f"{i}: {val}")
        i += 1
